[package]
name = "cmd_cache"
version = "0.1.0"
authors = ["Benoît Dejean <bdejean@gmail.com>", "Cyprien Le Pannérer <cyplp@free.fr>"]
license = "GPL-3.0"

[dependencies]

rust-crypto = "*"

tempdir = "*"

[dev-dependencies]
rand = "*"

